### ISSUE TITLE
conftest.py:186: TypeError 

### ISSUE THREAD

**Issue by g2gcio** [ElSnoMan/pyleniumio#105]
While trying the follow the example script provided at the Pylenium Gitbook site,  I ran into the following error.  Not sure where can we discuss this sort of issue:

>       py = Pylenium(py_config, test_case.logger)
E       TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by ElSnoMan** [comment]
Can you provide more information please?

* What does your project structure look like?
* How did you install Pylenium? (with pip, pipenv, etc.)
* What version of Python are you using?
* What is your OS?

Without more detailed info and repro steps I won't be able to help.

Thank you!

**Comment by g2gcio** [comment]
**Project Structure:** Just follow the example on https://elsnoman.gitbook.io/pylenium/getting-started/setup-pytest  except skipping Venv setup and also not using PIPENV.
**Installed Pylenium**  using PIP
**Python Version** is 3.8.1
**OS** is Windows 10

**Comment by ElSnoMan** [comment]
Can you show me the project structure that you have? Do you have a virtual environment?

**Comment by g2gcio** [comment]
I tried your tutorial on the Linux machine and it works! I also tried to set up a VENV with the latest Python v3.8.3.  but still having the same error ;-)  Let me know what I could try next 
=============================================
Folder PATH listing for volume Extra
Volume serial number is D438-0E84
E:.
|   conftest.py
|   drag_and_drop.js
|   pylenium.json
|   pyvenv.cfg
|   
+---.pytest_cache
|   |   .gitignore
|   |   CACHEDIR.TAG
|   |   README.md
|   |   
|   \---v
|       \---cache
|               nodeids
|               stepwise
|               
+---.vscode
|       settings.json
|       
+---Codes
|   |   test_google.py
|   |   test_qap_dev.py
|   |   
|   +---.pytest_cache
|   |   |   .gitignore
|   |   |   CACHEDIR.TAG
|   |   |   README.md
|   |   |   
|   |   \---v
|   |       \---cache
|   |               lastfailed
|   |               nodeids
|   |               stepwise
|   |               
|   \---__pycache__
|           test_google.cpython-38-pytest-5.4.2.pyc
|           
===================================================

**Comment by g2gcio** [comment]
I tried your tutorial on the Linux machine and it works! I also tried to set up a VENV with the latest Python v3.8.3.  but still having the same error ;-)  Let me know what I could try next 
=============================================
Folder PATH listing for volume Extra
Volume serial number is D438-0E84
E:.
|   conftest.py
|   drag_and_drop.js
|   pylenium.json
|   pyvenv.cfg
|   
+---.pytest_cache
|   |   .gitignore
|   |   CACHEDIR.TAG
|   |   README.md
|   |   
|   \---v
|       \---cache
|               nodeids
|               stepwise
|               
+---.vscode
|       settings.json
|       
+---Codes
|   |   test_google.py
|   |   test_qap_dev.py
|   |   
|   +---.pytest_cache
|   |   |   .gitignore
|   |   |   CACHEDIR.TAG
|   |   |   README.md
|   |   |   
|   |   \---v
|   |       \---cache
|   |               lastfailed
|   |               nodeids
|   |               stepwise
|   |               
|   \---__pycache__
|           test_google.cpython-38-pytest-5.4.2.pyc
|           
===================================================

**Comment by g2gcio** [comment]
I tried your tutorial on the Linux machine and it works! I also tried to set up a VENV with the latest Python v3.8.3.  but still having the same error ;-)  Let me know what I could try next 
=============================================
Folder PATH listing for volume Extra
Volume serial number is D438-0E84
E:.
|   conftest.py
|   drag_and_drop.js
|   pylenium.json
|   pyvenv.cfg
|   
+---.pytest_cache
|   |   .gitignore
|   |   CACHEDIR.TAG
|   |   README.md
|   |   
|   \---v
|       \---cache
|               nodeids
|               stepwise
|               
+---.vscode
|       settings.json
|       
+---Codes
|   |   test_google.py
|   |   test_qap_dev.py
|   |   
|   +---.pytest_cache
|   |   |   .gitignore
|   |   |   CACHEDIR.TAG
|   |   |   README.md
|   |   |   
|   |   \---v
|   |       \---cache
|   |               lastfailed
|   |               nodeids
|   |               stepwise
|   |

**Comment by g2gcio** [comment]
I tried your tutorial on the Linux machine and it works!
Back on my Windows 10, I installed latest python v3.8.3; set up a VENV and it works NOW!!!
Thanks!  Sorry for all unnecessary escalation :-(

**Comment by ElSnoMan** [comment]
I'm glad you were able to figure it out. Literally step one of the setup is the [Virtual Environment](https://elsnoman.gitbook.io/pylenium/getting-started/virtual-environments) and I do call it out as something **required** so when you said you followed the instructions except for that part, I was very confused. I even had the YouTube video as well that goes over how to set it up.
