### ISSUE TITLE
Catch AttributeError after switch window

### ISSUE THREAD

**Issue by den-cezar** [ElSnoMan/pyleniumio#114]
Just update to the pyleniumio ver.1.9.0.
After switch to other window, I'm caught this error.
![image](https://user-images.githubusercontent.com/17469276/85741503-287c9d00-b70b-11ea-9181-a6525cf72af9.png)

**Comment by ElSnoMan** [comment]
Good catch! It seems the "find all" function in PyCharm missed a `log.action()` line. I will fix this and push up 1.9.1 soon

**Comment by ElSnoMan** [comment]
Fixed: 1.9.1
