### ISSUE TITLE
Allure report integration

### ISSUE THREAD

**Issue by den-cezar** [ElSnoMan/pyleniumio#116]
Tell me please, exist a simple way to implement Allure report (http://allure.qatools.ru/). Instead of RP or keep them together?

**Comment by ElSnoMan** [comment]
Most likely. I don't use Allure myself, but there will be a lot of resources to help you integrate it. Remember that Pylenium is just a library, but pytest is the Testing Framework. Here's a video I found with a quick Google Search:

https://www.youtube.com/watch?v=kP-PnWBJPqA

**Comment by den-cezar** [comment]
Thank you, go to try it.
