### ISSUE TITLE
unconsitent tags between git repo and pypi

### ISSUE THREAD

**Issue by nfk** [ElSnoMan/pyleniumio#123]
From [git](https://github.com/ElSnoMan/pyleniumio/tags) I cannot see the tag `1.9.5` but pypi provides the pyleniumio `1.9.5` package.

```
pip list | grep pyleniumio
pyleniumio          1.9.5
```

I have some troubles to start with pylenium, and I try to fix my issues step by step ;)

**Comment by ElSnoMan** [comment]
I was only putting tags and releases on major changes. The major release was 1.9.0 and the next 5 were minor and not worth a changelog. However, I can see that at least adding tags would be helpful. Thank you for the feedback.
