### ISSUE TITLE
Test Results directory in setup fails intermittently

### ISSUE THREAD

**Issue by ElSnoMan** [ElSnoMan/pyleniumio#130]
This issue is not consistent, but sometimes the Test Results directories are not created or, at least, not created in time causing the setup to fail. This looks like an issue with race conditions, but right now we have

* pytest-xdist
* pytest-parallel

as the two plugins that allow you to run tests in parallel. This feature is considered "legacy" since it was one of the first features written. These folders were used to store log files and screenshots for each test, but logging now happens via the `logging` module so now these folders are _only_ used for screenshots if the test fails.

> So, we can either fix this issue, or we can create a new Feature Request suggesting a better, cleaner way to report logs and screenshots on failure.

```
project_root = '/home/runner/work/pyleniumio/pyleniumio'
request = <SubRequest 'test_run' for <Function test_element_parent_and_siblings>>

    @pytest.fixture(scope='session', autouse=True)
    def test_run(project_root, request) -> str:
        """ Creates the `/test_results` directory to store the results of the Test Run.
    
        Returns:
            The `/test_results` directory as a filepath (str).
        """
        session = request.node
        test_results_dir = f'{project_root}/test_results'
    
        if os.path.exists(test_results_dir):
            # delete /test_results from previous Test Run
            shutil.rmtree(test_results_dir, ignore_errors=True)
        if not os.path.exists(test_results_dir):
            # create /test_results for this Test Run
            make_dir(test_results_dir)
    
        for test in session.items:
            # make the test_result directory for each test
>           make_dir(f'{test_results_dir}/{test.name}')

conftest.py:111: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filepath = '/home/runner/work/pyleniumio/pyleniumio/test_results/test_element_with_no_siblings'

    def make_dir(filepath) -> bool:
        """ Make a directory.
    
        Returns:
            True if successful, False if not.
        """
        try:
>           os.mkdir(filepath)
E           FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/pyleniumio/pyleniumio/test_results/test_element_with_no_siblings'
```

**Comment by chingc** [comment]
I've come across this problem recently without parallelization.  I had some parametrize tests that would trigger this 100% of the time.  Sample code below.

I originally thought it was unsafe characters in the path causing `make_dir` to fail, but after looking up what characters were illegal in macOS apparently practically every character is allowed.

My second suspicion is that all the forward slashes in the URLs are somehow misinterpreted as being part of the path, causing `make_dir` to get confused and fail.

I couldn't figure out the exact problem.  I ended up by just avoiding parametrized tests.

I'm running macOS Big Sur 11.2.3, Python 3.6.8, and pyleniumio 1.12.2.

```
from urllib.parse import urlsplit

expected = [
    ('https://github.com/ElSnoMan/pyleniumio', ['https', 'github.com', '/ElSnoMan/pyleniumio', '', '']),
    ('https://www.google.com', ['https', 'www.google.com', '', '', ''])
]

@pytest.mark.parametrize('url, split', expected)
def test_urlsplit(url, split):
    assert list(urlsplit(url)) == split
```

**Comment by ElSnoMan** [comment]
Ah, `make_dir()` is unable to make a directory with the characters in `['https', 'github.com', '/ElSnoMan/pyleniumio', '', '']` which may or not be tied to the intermittent failures. One solution that was part of one of the old PRs was to use `test.originalname` instead of `test.name`

```python
make_dir(f'{test_results_dir}/{test.originalname}')
```

The only problem there is any parametrized tests results would be overriden by the last test case instead of each getting their own folder. For example, given this test:

```python
examples = [0, 1, 2]

@pytest.mark.parametrize('num', examples)
def test_add(num):
    assert num > 0
```

The current functionality would create three folders under `test_results`:

* `test_add[0]`
* `test_add[1]`
* `test_add[2]`

With `test.originalname`, there would only be a single _test name_ and each test case would write to it:

* `test_add`

However, we don't necessarily need to make these folders anymore. Their only real use is storing the screenshots of failed tests. I'd be ok removing this functionality, but we would need to solve how to take screenshots on failure in an elegant way.

What do you think, @chingc ?

**Comment by chingc** [comment]
It'd be a shame to lose screenshots.  Perhaps `test.name` could be slugified.  That way all the unsafe characters would be replaced.   Only thing is if there's a lot of characters being replaced (like in my URL example) the resulting name might look weird.  There's also the possibility that two unique strings could become identical after being slugified.

**Comment by chingc** [comment]
This problem happened to me today when I used the `-n` option and I noticed that the exception was the same for every error.

Could the problem be as simple as `make_dir(f'{test_results_dir}/{test.name}')` not being thread safe?

```
ERROR bentobox/apps/webpack/tests/test_webpack_admin.py::test_save_unreachable - OSError: [Errno 22] Invalid argument: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/main/tests/test_datetime.py::test_datetime_sameness - FileNotFoundError: [Errno 2] No such file or directory: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/webpack/tests/test_webpack_admin.py::test_save_reachable - OSError: [Errno 22] Invalid argument: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/bento_admin/tests/test_url_utils.py::test_url_normalize_1 - OSError: [Errno 22] Invalid argument: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/main/tests/test_miscellaneous.py::test_bentobox_user_agent - OSError: [Errno 22] Invalid argument: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/main/tests/test_urllib_to_requests.py::test_urlencode_to_requests - FileNotFoundError: [Errno 2] No such file or directory: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/main/tests/test_miscellaneous.py::test_simple_timer - OSError: [Errno 22] Invalid argument: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/main/tests/test_datetime.py::test_strftime_sameness - OSError: [Errno 22] Invalid argument: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/webpack/tests/test_webpack_admin.py::test_bentobox_revision - OSError: [Errno 22] Invalid argument: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
ERROR bentobox/apps/webpack/tests/test_webpack_admin.py::test_bentobox_revision_detached - FileNotFoundError: [Errno 2] No such file or directory: '/Users/chingchow/Documents/bentobox/test_results/test_save_reachable'
```

**Comment by chingc** [comment]
Will let you know if I still hit that error!

**Comment by chingc** [comment]
@ElSnoMan I don't know about you, but it's been a while since I've seen this error.  v1.12.5 might have fixed it!

**Comment by chingc** [comment]
@ElSnoMan Nevermind, I just hit this today.  :(

I don't understand why it's throwing `FileExistsError` when `exist_ok` is set to `True` ...

```
self = PosixPath('/home/ubuntu/bentobox/test_results/test_patch_is_active')
mode = 511, parents = True, exist_ok = True

    def mkdir(self, mode=0o777, parents=False, exist_ok=False):
        """
        Create a new directory at this given path.
        """
        if self._closed:
            self._raise_closed()
        try:
>           self._accessor.mkdir(self, mode)
E           FileExistsError: [Errno 17] File exists: '/home/ubuntu/bentobox/test_results/test_patch_is_active'

/usr/lib/python3.8/pathlib.py:1284: FileExistsError
_ ERROR at setup of GoogleInventoryAPIServiceTestCase.test_incorrect_update_response_will_log_warning _
[gw1] linux -- Python 3.8.5 /home/ubuntu/venv/bin/python3

project_root = '/home/ubuntu/bentobox'
request = <SubRequest 'test_run' for <TestCaseFunction test_update_when_valid>>

    @pytest.fixture(scope='session', autouse=True)
    def test_run(project_root, request) -> str:
        """Creates the `/test_results` directory to store the results of the Test Run.
    
        Returns:
            The `/test_results` directory as a filepath (str).
        """
        session = request.node
        test_results_dir = f'{project_root}/test_results'
    
        if os.path.exists(test_results_dir):
            # delete /test_results from previous Test Run
            shutil.rmtree(test_results_dir, ignore_errors=True)
    
        Path(test_results_dir).mkdir(parents=True, exist_ok=True)
    
        for test in session.items:
            # make the test_result directory for each test
>           Path(f'{test_results_dir}/{test.name}').mkdir(parents=True, exist_ok=True)

conftest.py:99: 
```
