### ISSUE TITLE
Documentation-only PRs should not trigger the Testing CI Workflow

### ISSUE THREAD

**Issue by ElSnoMan** [ElSnoMan/pyleniumio#135]
## Description

Currently, on _any_ push or PR to master, the main Build and Test workflow is triggered. However, this is unnecessary for PRs that are documentation-only (aka only update documentation). This is a waste of time and resources. How should we solve this?

## Possible Solutions

* Include an `ignore` parameter in `build-and-test.yml`
* Specific naming convention or tag for documentation-only branches/PRs

## Notes

A lot of documentation can be updated right in the Project Root or `/docs` directory. However, do know that we house our public-facing documentation in Gitbook. This creates a commit straight to master. Something to consider.

**Comment by chingc** [comment]
GH-Actions allows you to ignore changes to certain paths.  You can have it completely ignore the `/docs` directory to avoid triggering a workflow.

Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
