### ISSUE TITLE
Use Pipfile to dynamically know which packages to include in setup.py

### ISSUE THREAD

**Issue by ElSnoMan** [ElSnoMan/pyleniumio#142]

**Comment by gleekzorp** [comment]
I don't fully understand the `setup.py` so this could be wrong.  As I was doing some research I found these docs [pip list](https://pip.pypa.io/en/stable/reference/pip_list/).  With some playing I found this command `pip list --not-required --format=json`.

- Sample Idea
```python
import subprocess
import json


def get_list_of_packages():
    output = subprocess.getoutput("pip list --not-required --format=json")
    packages = []
    not_needed = ['setuptools', 'pip']
    for item in json.loads(output):
        if item['name'] not in not_needed:
            packages.append(item['name'])
            print(item)

    print(packages)
```

- While testing with your code I was getting more data telling me about my version of pip which ended up causing an issue when trying to convert the string.
```
[{"name": "axe-selenium-python", "version": "2.1.6"}, {"name": "click", "version": "7.1.2"}, {"name": "Faker", "version": "4.14.0"}, {"name": "pip", "version": "20.1.1"}, {"name": "pydantic", "version": "1.7.1"}, {"name": "pyfiglet", "version": "0.8.post1"}, {"name": "pytest-parallel", "version": "0.1.0"}, {"name": "pytest-reportportal", "version": "5.0.5"}, {"name": "pytest-xdist", "version": "2.1.0"}, {"name": "setuptools", "version": "47.1.0"}, {"name": "webdriver-manager", "version": "3.2.2"}]
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/Users/gleek/Downloads/pyleniumio-master/venv/bin/python3 -m pip install --upgrade pip' command.
```
- This was my fix for that issue.  Might want to do a different way of splitting out the array from the string, but this seems to work.
```python
import subprocess
import json


def get_list_of_packages():
    output = subprocess.getoutput("pip list --not-required --format=json")
    packages = []
    not_needed = ['setuptools', 'pip']
    for item in json.loads(output.split('\n')[0]):
        if item['name'] not in not_needed:
            packages.append(item['name'])
            print(item)

    print(packages)
```

I'm sure you could whip up some Carlos magic to make it look better.  I hope this helps.

**Comment by ElSnoMan** [comment]
@gleekzorp Feel free to create a Pull Request with your proposed changes! Ideally, this would use `pipenv` since that's the package manager we're using. If we could leverage the Pipfile, that should make this a lot easier

**Comment by ElSnoMan** [comment]
We're now using `Poetry` as the package manager instead of `Pipenv`. This will change the implementation quite a bit, but the concepts are the same
