### ISSUE TITLE
Support for Electron driver

### ISSUE THREAD

**Issue by rsporny** [ElSnoMan/pyleniumio#144]
Electron is a chromium-based desktop app framework which we can easily automate with selenium just by overriding chrome browser binary path. In pylenium it is done by adding these parameters:

`--remote_url=http://localhost:9515`  --chromedriver server
`--caps='{"goog:chromeOptions": {"binary": "path"}}'`  --path to electron binary

The only issue with such setup is `webdriver.maximize_window()` which throws `WebDriverException` because it's done a bit differentely in destkop app than in actual browser. My quick-win solution is to catch and log that exception - what do you think?

**Comment by ElSnoMan** [comment]
@rsporny So how do you actually maximize the window for electron?

**Comment by rsporny** [comment]
this opens app in full screen mode:
`self.webdriver.execute_script("require('electron').remote.BrowserWindow.getFocusedWindow().setFullScreen(true);")`

**Comment by ElSnoMan** [comment]
This has been completed and released 😄
