### ISSUE TITLE
Pyleniumio doesn't install drivers

### ISSUE THREAD

**Issue by fericsepi** [ElSnoMan/pyleniumio#149]
Hey there, just trying this lib out, looks pretty good, but I don't think it's installing anything in terms of driver or browser (as the docs claims)
```terminal
You don't need to worry about installing any driver binaries like chromedriver. Pylenium does this all for you automatically :)
```

So I'm installing this on a docker image (CentOS 8) via `pip install pyleniumio` but then when I run the tests it cannot find chrome, I ssh-d in to the container and confirmed that chrome is indeed not installed.

```terminal
>           raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
E           ValueError: Could not get version for Chrome with this command: google-chrome --version || google-chrome-stable --version
```

**Comment by ElSnoMan** [comment]
You need to make sure your machine (aka the docker container) has the actual browser installed. Pylenium handles installing and managing the driver binaries for you, but the drivers require the their corresponding browsers so they can drive them

**Comment by ElSnoMan** [comment]
I'm closing this issue since there's been no response and this is not a Pylenium issue

**Comment by fericsepi** [comment]
Thanks, I didn't notice the reply until now - I eventually gave up on Pyleniumio
