### ISSUE TITLE
Module not found in version 1.12.1

### ISSUE THREAD

**Issue by serdnago** [ElSnoMan/pyleniumio#152]
Installing the latest version of pyleniumio (1.12.1) throws this error:
..\conftest.py:34: in <module>
    from pylenium.a11y import PyleniumAxe
E   ModuleNotFoundError: No module named 'pylenium.a11y'

**Comment by ElSnoMan** [comment]
Sounds like you already had `pyleniumio` installed. In that case, make sure you update your `conftest.py` file to the latest one using

```python
$ pylenium init -c
```

**Comment by serdnago** [comment]
> Sounds like you already had `pyleniumio` installed. In that case, make sure you update your `conftest.py` file to the latest one using
> 
> ```python
> $ pylenium init -c
> ```

Yes, that was the issue! Thank you for your fast response. BTW, this project rocks!!!
