### ISSUE TITLE
Extend Element class with eq(n) method

### ISSUE THREAD

**Issue by ktarantowicz** [ElSnoMan/pyleniumio#154]
Suggestion to extend Element class to allow to access element at specified index, not only the first or last one.

```
def eq(self, index: int) -> 'Element':
    """ Gets the element from the list at specified index.
    Raises:
        `IndexError` if the list is shorter than given index.
    """
    if self.length() > index:
        return self._list[index]
    else:
        raise IndexError(f'Cannot get eq({index}) from too short list.')
```

**Comment by ElSnoMan** [comment]
@ktarantowicz You can already do this! `Elements` is just a list, so you can index into it like any other Python list. `.first()` and `.last()` are just convenience methods.

## Examples

To get the `first` element from `Elements`:

```python
py.find('a').first()

# ---or---

py.find('a')[0]
```

To get the `last` element from `Elements`:

```python
py.find('a').last()

# ---or---

py.find('a')[-1]
```

To get any other element by index in the list, just index into it like any other list in python:

```python
# get the 4th element
py.find('a')[3]

# get the 2nd to last element
py.find('a')[-2]
```

**Comment by ElSnoMan** [comment]
I'm closing this ticket since it's not an issue and there's been no response.
