### ISSUE TITLE
Is it possible to use the same driver instance across multiple test functions?

### ISSUE THREAD

**Issue by pmneve** [ElSnoMan/pyleniumio#158]
Am building testing for a Wagtail based museum style exhibit system.  The generated exhibit site is static from the visitor point of view.  Would like to avoid restarting the browser and calling up the exhibit site for each test method if possible.
When I try to set the fixture that opens the exhibit to scope=session or class, pytest complains that the py fixture is function level so can't do that...

**Comment by ElSnoMan** [comment]
@pmneve In professional test automation, sharing data or objects across multiple tests is a really bad practice. This is one of the reasons Pylenium doesn't allow this by default. However, you _can_ write your own functions to bypass this behavior (although I _still_ wouldn't recommend it)

To do this, you wouldn't use the `py` fixture (or any other function-level fixtures).
Instead, you would need to make an instance of `PyleniumConfig` and `Pylenium` somewhere:

```python
config = PyleniumConfig()
py = Pylenium(config)

def test_one():
    py.visit('website.com')
    assert py.should().contain_title('Website Title')

def test_two():
    py.get('#button').click()
    assert py.get('#image').should().be_visible()
```

**Comment by pmneve** [comment]
Carlos,
I agree it is not good practice in almost all circumstances.  The only reason I’m considering it here is that the target site is totally read only to the public visitor (not even any configuration options) and I can get better visibility to the number of test cases (to help satisfy metrics needs, fuzzy at best but there you are), as well as much faster execution, by splitting several steps in single test_... function to separate methods.
Thanks for the tip and the warning!
pat

--
Patrick M Neve
Senior QA Automation Engineer
pneve@bepress.com<mailto:jgbankier@bepress.com>
Tel. : +1 510 570 3436
Digital Commons, powered by bepress | Elsevier
2100 Milvia Street, Suite 300, Berkeley, CA 94704
