### ISSUE TITLE
Creating new windows and tabs

### ISSUE THREAD

**Issue by rafutek** [ElSnoMan/pyleniumio#159]
I was wondering if creating new windows and tabs was going to be included in Pylenium.

Indeed, we can switch to a created window with `switch_to.window`, but how can we create that window without calling the webdriver ?

**Comment by ElSnoMan** [comment]
@rafutek why are you wanting to create a new, empty window? That sounds like a very niche thing to do, so I'm fine not natively including it in Pylenium - especially if you can already do this with WebDriver

**Comment by rafutek** [comment]
@ElSnoMan  It would be more like visiting a web page on a new window or new tab, like "open in a new window/tab".

As Pylenium currently allows to switch windows, I was wondering why it did not allow to create windows. But indeed, we can directly use Selenium to create a new window and then switch to it with Pylenium.

**Comment by ElSnoMan** [comment]
That is not a common thing to do and not one I want promoting when there's usually not a good reason to do this.

For anyone that really really needs to do this, they can easily write their own function with Pylenium or Selenium

**Comment by ElSnoMan** [comment]
For anyone looking to do this, you have some simple solutions:

1. Use the browser's keyboard shortcut

    * `CTRL + t` might not work on all browsers
    * `CTRL` is for Windows, but it might work in other OS (For example, `Keys.COMMAND` on Mac)

```python
py.get('body').type(Keys.CONTROL + 't');
```

2. Execute javascript

```python
py.execute_script("window.open('https://google.com', '_blank');")
```
