### ISSUE TITLE
UPD Links in Docs in Readme.md files

### ISSUE THREAD

**Issue by den-cezar** [ElSnoMan/pyleniumio#160]
Hi, please update the link into documentation https://github.com/ElSnoMan/pyleniumio/tree/master/docs
- pylenium.json - This is the configuration file for Pylenium  -- link is not work;
- pytest.ini - This is the configuration file for pytest and is used to connect to ReportPortal -- link is not work;

Thanks for your works! 

![image](https://user-images.githubusercontent.com/17469276/108226047-3329ed80-7145-11eb-9745-a584fccb1667.png)

**Comment by ElSnoMan** [comment]
Great catch! That should be fixed now https://elsnoman.gitbook.io/pylenium/

**Comment by den-cezar** [comment]
Maybe links should go to these places:
- https://github.com/ElSnoMan/pyleniumio/blob/master/docs/configuration/pylenium.json.md 
- https://github.com/ElSnoMan/pyleniumio/blob/master/docs/configuration/report-portal.md ?

**Comment by ElSnoMan** [comment]
Even better! Thanks for posting the links 😄

**Comment by den-cezar** [comment]
Thank you too :)
