### ISSUE TITLE
Documentation about manipulating elements

### ISSUE THREAD

**Issue by henningway** [ElSnoMan/pyleniumio#162]
When evaluating Pylenium we struggled to find out how to manipulate elements, e.g. type some text in an \<input\>. It seems that Pylenium does not care about this use case at all. After some digging we learned that all we need to do is to use the underlying Selenium WebElement:

`py.get('input[name="username"]').webelement.send_keys('admin')`

I wonder if this is a deliberate design decision? Does Pylenium encourage using the Selenium APIs? Or is the scope of Pylenium to be a test tool for websites with mostly static content?

In any case I think new users would benefit if the documentation had a section about this topic. What do you think?

**Comment by vernko** [comment]
Per your example, here is a link from the docs on how to type into a field.

https://elsnoman.gitbook.io/pylenium/element-commands/type

**Comment by henningway** [comment]
Very helpful indeed, thank you!

Two pairs of eyes did not find this, so I think it should be more prominent, probably in section _4. Writing Tests with Pylenium_. But I don't want to encourage pylenium users to send a contact form or something and spam the domain owners. Maybe we should add a new, second example 🤔?

**Comment by ElSnoMan** [comment]
https://elsnoman.gitbook.io/pylenium/

Usually people start with the Home or Welcome page which has two examples and even a setup video that goes through this.

It'd be different if many people were struggling to find `.type()`, but most people see it on the first page and the videos. However, I do think it would be helpful to have a "Recipes" section for how to do certain things which i think would resolve this issue as well

**Comment by ElSnoMan** [comment]
Added another test example and called out the different Commands like `.type()` and the `Should` objects.

**Comment by henningway** [comment]
Awesome :). You are probably right, I happen to have skimmed past this. The video is great by the way!
