### ISSUE TITLE
Refactor Browser Class Selenium 4

### ISSUE THREAD

**Issue by vernko** [ElSnoMan/pyleniumio#171]
We need to refactor the Browser class for Selenium 4. The `DesiredCapabilities` has been deprecated and replaced by `Options` for the different browser (i.e _Chrome – ChromeOptions, Firefox – FirefoxOptions, Internet Explorer (IE) – InternetExplorerOptions, Safari – SafariOptions, Microsoft Edge – EdgeOptions_)

**Comment by ElSnoMan** [comment]
Resolved as of `v1.14.3`
