### ISSUE TITLE
TakeElementScreenshot for Selenium 4

### ISSUE THREAD

**Issue by vernko** [ElSnoMan/pyleniumio#173]
Selenium 4 adds the ability to capture a screenshot of WebElement

**Comment by ElSnoMan** [comment]
In Pylenium, we currently do `Element.screenshot()`. Is this different than that, @vernko?

**Comment by vernko** [comment]
I’d had to look at the documentation. I think it’s slightly different, but
haven’t looked at this in awhile. So not sure.
