### ISSUE TITLE
Have an input type=checkbox that is activated by a hover. Can't check it.

### ISSUE THREAD

**Issue by pmneve** [ElSnoMan/pyleniumio#185]
The element _is_ the element where the hover is detected.  
I'm getting the 'element not interactable' error when attempting to check or click it.

Here is html snippet before hovering:
`                    <li>
                        <div class="field">
                            <label>Publish</label>
                            <div class="field-content">
                                <div class="input">
                                    <input type="checkbox" name="is_publish" />
                                </div>
                                <p class="help">
                                    If checked, items will automatically be made public.
                                </p>
                            </div>
                        </div>
                    </li>
`
The input with name 'is_publish' has to be hovered over to accept check or click.

Here is the html when the element is hovered over:
![2021-04-19_14-09-13](https://user-images.githubusercontent.com/3780424/115304013-3c214600-a119-11eb-9277-85a1252e778e.png)

Any suggestions?

**Comment by pmneve** [comment]
I found it.
Must drop to selenium webdriver and use action chain:
`        driver = self.py.webdriver
        a = ActionChains(driver)
        target = driver.find_element("css selector", "input[name='is_publish']")
        if publish:
            if not target.is_selected():
                a.move_to_element(target).click().perform()
        else:
            if target.is_selected():
                a.move_to_element(target).click().perform
`
alrighty, then!

**Comment by vernko** [comment]
I was going to suggest that you use some kind of command from Action
Chains. Glad you found something!

**Comment by pmneve** [comment]
@vernko Thanks!!
