### ISSUE TITLE
"settings are not configured properly" I get this issue because from conftest configuration

### ISSUE THREAD

**Issue by ssandr1kka** [ElSnoMan/pyleniumio#191]
Hi, 
You have already answered my previous [issue](https://github.com/ElSnoMan/pyleniumio/issues/165). However, doing that I have faced one problem.
Once I copy, paste all fixtures in conftest, with my original code, I get following error:
`
../lang/lib/python3.8/site-packages/django/conf/__init__.py:79: in __getattr__
    self._setup(name)
../lang/lib/python3.8/site-packages/django/conf/__init__.py:60: in _setup
    raise ImproperlyConfigured(
E   django.core.exceptions.ImproperlyConfigured: Requested setting REST_FRAMEWORK, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
`

This is my code in the conftest before I add pylenium:

```

import uuid
import pytest

from django.db.models.signals import (
    pre_save,
    post_save,
    pre_delete,
    post_delete,
    m2m_changed,
)
from jwt_auth.models import User as AuthUser

from profiles.models import Profile
from profiles.tests.factories import create_profile


USER_UUID = uuid.uuid4()
PROFILE_UUID = uuid.uuid4()

def create_user(user_id: uuid.UUID, email: str = "example@test.com"):
    """Create a test auth user."""
    return AuthUser(str(user_id), email)


@pytest.fixture()
def test_user() -> AuthUser:
    """Create test user."""
    return create_user(USER_UUID)


@pytest.fixture()
def test_profile() -> Profile:
    """Create test profile."""
    return create_profile(
        profile_id=PROFILE_UUID,
        data={
            "user_id": str(USER_UUID),
        },
    )
```

Any suggestions what would fix the situation?

**Comment by ElSnoMan** [comment]
Were you able to figure this out?
