### ISSUE TITLE
driver.py:find()

### ISSUE THREAD

**Issue by darylkell** [ElSnoMan/pyleniumio#196]
pyleniumio/driver.py:

line 363 is currently: `elements = self.webdriver.find_element(by, css)`
should be: `elements = self.webdriver.find_elements(by, css)`

**Comment by ElSnoMan** [comment]
Good catch! This will be fixed in the next release

**Comment by ElSnoMan** [comment]
@darylkell This is now fixed in `v1.12.6`

https://pypi.org/project/pyleniumio/
