### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by medurasharath777** [ElSnoMan/pyleniumio#231]
how to handle proxy issue showing error like conection error

**Comment by medurasharath777** [comment]
cc @ElSnoMan

**Comment by ElSnoMan** [comment]
Can you provide more details? I don't know what you mean by "proxy issue"

**Comment by medurasharath777** [comment]
when I connected through VPN issues shows like below
FAILED Funtional_Test_Suit/main.py::test_google_search - requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=4...
ERROR Funtional_Test_Suit/main.py::test_google_search - requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=44...

**Comment by ElSnoMan** [comment]
What does the test look like?

I noticed that you put it in a main.py file when that's not recommended with Pylenium. However, this isn't a Pylenium issue - it may not even be a Selenium issue.

If the test works off VPN, then your VPN is not allowing the test to access the site or start the web session. The point is that this error is more about your environment than the library or website

**Comment by medurasharath777** [comment]
So For the environment we need to provide proxies right
how to give that

**Comment by medurasharath777** [comment]
Is there any option to add Proxy

**Comment by medurasharath777** [comment]
now getting error like below
selenium.common.exceptions.WebDriverException: Message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

**Comment by ElSnoMan** [comment]
Using this article from [Browserstack](https://www.browserstack.com/guide/set-proxy-in-selenium) about adding a proxy argument, you would do this in Pylenium by leveraging `pylenium.json`. Here are the official docs for the pylenium.json config file: https://docs.pylenium.io/configuration/driver

Under the `driver.options` field, add this:

```javascript
"options": ["--proxy-server=PROXY"]
```

> 💡 Replace `PROXY` with your actual proxy value

For example:

```javascript
"driver": {
    "browser": "chrome",
    "remote_url": "",
    "wait_time": 10,
    "page_load_wait_time": 0,
    "options": ["--proxy-server=11.456.448.110:8080"],
    "experimental_options": null,
    "capabilities": {},
    "extension_paths": [],
    "version": "latest"
  }
```

**Comment by medurasharath777** [comment]
Do i need to update again like pip install pyleniumio

**Comment by medurasharath777** [comment]
getting error like this selenium.common.exceptions.WebDriverException: Message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

**Comment by ElSnoMan** [comment]
No, that just comes with Pylenium. If you don't provide more details, I can't help. I don't know why you're getting that error

**Comment by ElSnoMan** [comment]
No movement. Closing
