### ISSUE TITLE
latest `reportportal / agent-python-pytest` update introduced breaking change to conftest import

### ISSUE THREAD

**Issue by lolrenx** [ElSnoMan/pyleniumio#252]
https://github.com/reportportal/agent-python-pytest/issues/303

reportportal 5.0.12 => 5.1.0 

```
conftest.py:15: in <module>
    from pytest_reportportal import RPLogger, RPLogHandler
E   ImportError: cannot import name 'RPLogger' from 'pytest_reportportal' (.../venv/lib/python3.10/site-packages/pytest_reportportal/__init__.py)
```

changing my conftest from
`from pytest_reportportal import RPLogger, RPLogHandler`

to
`from reportportal_client import RPLogger, RPLogHandler`
fixed it

**Comment by ElSnoMan** [comment]
@lolrenx could you review PR #254 when you get a chance? It should fix this problem! Great catch btw, and thanks for reporting it 🙏🏽

**Comment by lolrenx** [comment]
> @lolrenx could you review PR #254 when you get a chance? It should fix this problem! Great catch btw, and thanks for reporting it 🙏🏽

No worries, this broke our CI so I might as well share the love !
