### ISSUE TITLE
Doesn't work with headless chrome on Windows Subsystem for Linux 2.

### ISSUE THREAD

**Issue by jcoombes** [ElSnoMan/pyleniumio#256]
When running pyleniumio with python 3.9 on wsl2 ubuntu focal, installing and running chrome from the command line doesn't work.

Specifically, when I create a tests/ directory and try the test_google_search.py hello world example - it gives me this error.

E         (unknown error: DevToolsActivePort file doesn't exist)
E         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

StackOverflow tells me this error is because we aren't setting chrome options.
https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t

**Comment by jcoombes** [comment]
okay, I think this might actually be a feature rather than a bug. 
 
 I get an error when running the chained `.type('puppies')` method, 
 just asking for `py.get("[name='q']")` works fine.

*** selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable

So I think this error is saying, 'if you are running a headless browser, then you can not type, which is the system working as intended, PEBKAC.'

**Comment by ElSnoMan** [comment]
@jcoombes you should still be able to type and click on things when in headless mode. Headless does behave slightly differently obviously, but most things should work.

Unfortunately, I don't have a Windows 10 + WSL2 setup so I can't help test or debug this.
