### ISSUE TITLE
How to Add Chrome Binary Location in   "seleniumwire_options": {} or in local_path

### ISSUE THREAD

**Issue by psarangi550** [ElSnoMan/pyleniumio#265]
Hi Carlos,

Thanks for the Tutorial, very helpful 👍 

I don't have Chrome Binary installed on my Webtop, Instead, I am using Brave, But I am unable to comprehend where to provide options.binary_location path in pylenium.json.

Is this need to be provided in the  "seleniumwire_options": {} or in local path, if yes what's the Syntax we have to use?

#Sample code in selenium
################################

import pytest
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

driver=None

@pytest.fixture
def setUp01():
    global driver
    options=Options()
    options.binary_location = "C:\\Users\\611903295\\AppData\\Local\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
    driver_loc="C:\\Users\\611903295\\Downloads\\python_BDD_Testing\\chromedriver.exe"
    driver=webdriver.Chrome(options=options,executable_path=driver_loc)
    driver.get("https://www.google.com/")
    yield driver
    driver.close()

def test_chrome(setUp01):
    # global driver
    assert setUp01.current_url == "https://www.google.com/"

**Comment by eformo** [comment]
on macos or linux put it into the `local_path` key.  once pylenium is ran the first time it will download the driver and put it into `.wdm` directory, then you can update your `pylenium.json`.  

Here is mine as an example:
```json
cat ../pylenium.json 
{
  "driver": {
    "browser": "firefox",
    "remote_url": "",
    "wait_time": 10,
    "page_load_wait_time": 10,
    "options": ["--ignore-certificate-errors"],
    "experimental_options": null,
    "capabilities": {
      "ACCEPT_SSL_CERTS": true,
      "ACCEPT_INSECURE_CERTS": true
    },
    "extension_paths": [],
    "version": "latest",
    "webdriver_kwargs": {},
    "local_path": ".wdm/drivers/chromedriver/mac64/97.0.4692.71/chromedriver"
  },
```

**Comment by ElSnoMan** [comment]
You can set this in the `capabilities` portion of pylenium.json:

```javascript
{"chrome.binary": "C:\Users\611903295\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe"}
```

**Comment by psarangi550** [comment]
Thanks That's helps a lot
