### ISSUE TITLE
Start Chrome/Webview early.

### ISSUE THREAD

**Issue by benkey0** [ElSnoMan/pyleniumio#272]
Hi,

I am attempting to time how long a certain test takes. (Please suggest if a better way of timing exists!)

For example my code currently : 

```
import time
def test_bing(py):
    tic = time.perf_counter()
    py.visit('https://www.bing.com')
    toc = time.perf_counter()
    print(f"Loaded bing in  {toc - tic:0.4f} seconds")
```

Now the result of this may be : 

`Process finished with exit code 0
PASSED                                          [100%]
Loaded bing in  3.4175 seconds`

How would I go about starting Chrome early? the 3.4 seconds above around 80% of this is just the chrome window starting. I want to assume that this is already started as would a real user.

Apologies if this is an obvious one! First time using pyleniumio.

**Comment by benkey0** [comment]
Thank you for your response on this, 

I didn't even think to "visit" the page before starting the timer. 

Yes, my example wasn't fantastic!

I have been playing around with this more and am making progress. 

Thanks for your help. Closing issue.

**Comment by ElSnoMan** [comment]
Not a problem! Thanks for using Pylenium and opening an Issue with your questions 😄 I'm happy to help any way I can
