### ISSUE TITLE
[Feature request] Support specifying the driver executable path

### ISSUE THREAD

**Issue by vincent-olivert-riera** [ElSnoMan/pyleniumio#281]
It would be nice if we could specify the path to the driver executable from `pylenium.json`. For instance:

```
{
  "driver": {
    "webdriver_executable_path": "/usr/local/bin/chromedriver_modified"
  }
}
```

If that option is specified, pylenium won't try to download the driver and it will just use that one.

That will solve two problems:
1. In https://chromedriver.storage.googleapis.com there isn't any version of ChromeDriver for Linux aarch64, so the automatic mechanism of pylenium to download the driver does not work.
2. Users cannot use their own patched driver.

**Comment by ElSnoMan** [comment]
You can use local_path
https://github.com/ElSnoMan/pyleniumio/discussions/213#discussioncomment-1416123

**Comment by vincent-olivert-riera** [comment]
> You can use local_path [#213 (comment)](https://github.com/ElSnoMan/pyleniumio/discussions/213#discussioncomment-1416123)

Ah, that was it! I was reading the description of all the options for the driver here: https://docs.pylenium.io/configuration/driver

Since the `local_path` does not have a description I missed it.

Thanks!
