### ISSUE TITLE
README missing critical step in Quick Start

### ISSUE THREAD

**Issue by chingc** [ElSnoMan/pyleniumio#283]
The Quick Start section of the main README at https://github.com/ElSnoMan/pyleniumio is missing `pylenium init` which results in the error:

```
fixture 'py' not found
```

**Comment by ElSnoMan** [comment]
Great catch! Our official docs look good: https://docs.pylenium.io/

But the README of the repo is not up-to-date as you've seen. I will get this updated.

Thanks!
