### ISSUE TITLE
NO SSL, slow driver execution

### ISSUE THREAD

**Issue by vrapsa** [ElSnoMan/pyleniumio#294]
Hey! First of all wanna say thanks for this awesome framework looks like Selenide on Java!
My issue is that when i use my test_method(py) my test is actually super slow,  but my internet connection is good. I find one possible issue like i see no SSL cert while executing tests. Might be reason here im not sure.
My project is fully clear: install selenium, pytest and pylenium, nothing more. Used guidline pylenium getting started aswell.
There is no SSL cert any site, even on qap.dev while executing.

**Comment by ElSnoMan** [comment]
Pylenium comes with pytest and selenium already, so no need to install them
separately.

Could you post a snippet of your code along with the test duration? It
would also be helpful to see the speed you're looking for and how you're
checking for the SSL.

Basically, the more details you can share the better I can debug and solve
the problem.

Thank you!

**Comment by vrapsa** [comment]
def test_try(py):
    py.visit("https://www.dns-shop.ru/")
    py.getx("//a[@class='ui-link menu-desktop__root-title' and text()='Компьютеры']").click()

17 seconds to pass the test with Pylenium, but if i go to my chrome locally to check loading speed its highly fast with SSL.

![image](https://user-images.githubusercontent.com/117261052/199488905-80531197-bbe2-40c7-8d58-30c18dadb60f.png)

**Comment by vrapsa** [comment]
![image](https://user-images.githubusercontent.com/117261052/199489551-9493f9c2-b98b-4246-a3fe-4e95288bfd9c.png)

**Comment by marksmayo** [comment]
I've run into this now as well, running it, and the screen is full of the certificate issues.  Has Seleniumwire changed what they do, or is this something else?

**Comment by ElSnoMan** [comment]
I'm also experiencing slowness. I'll take a look and see if it's SeleniumWire. If so, which it seems to be, then I'll add a flag to use Selenium or SeleniumWire

**Comment by ElSnoMan** [comment]
https://github.com/ElSnoMan/pyleniumio/releases/tag/v1.18.0
