### ISSUE TITLE
Error runing pylenium: No module named pkg_resources

### ISSUE THREAD

**Issue by jeremy886** [ElSnoMan/pyleniumio#326]
I followed the video and tutorial on [Pylenium](https://docs.pylenium.io/) but get this error: No module named pkg_resources

It took me a while to dig around but to no avail. Then I tried "pip install setuptools". Voila, it worked.

Is it a bug?

I'm on MacBook Pro M3.

**Comment by ElSnoMan** [comment]
Sounds like an issue with how you installed Python
