### ISSUE TITLE
📝 📝  Typo and error in https://docs.pylenium.io/

### ISSUE THREAD

**Issue by RichLuna** [ElSnoMan/pyleniumio#328]
Found a typo and an error in the documentation.

In the page for the Driver.should method (https://docs.pylenium.io/driver-commands/should), the example for the .have_url() method is using a .have_title() method instead.

![drivershould](https://github.com/ElSnoMan/pyleniumio/assets/10376250/a70fd55b-6380-4fa0-9543-a1be9411ceb0)

In the wait documentation page (https://docs.pylenium.io/driver-commands/wait) it mentions the phrase "Directly from Seleniujm" Instead of "Directly from Selenium".

![selenijum](https://github.com/ElSnoMan/pyleniumio/assets/10376250/79e40079-a5ad-416a-9ca6-b16eea9521d1)

I'd really like to help correcting this kind of small errors by myself. Unfortunately I can't find the source for docs.pylenium.io since it doesn't seem to be the /docs files. If you could point me towards instructions on how to fix this kind of errors I would do PRs in the future.

**Comment by ElSnoMan** [comment]
Great catches! Unfortunately, I've been using Gitbook for documentation and it isn't synced with the repo (where the original `/docs` came from). I'll make the changes for now, but I'll need to revisit how docs are done when I have time

**Comment by ElSnoMan** [comment]
Docs have been updated
