### ISSUE TITLE
No way to clear file input

### ISSUE THREAD

**Issue by Vhyseris** [ElSnoMan/pyleniumio#338]
I have on my website a multiple file input, on which I call the upload() method.

First call of uplaod() works fine.
Then on my second call( the input has still as value the first file) upload() uploads so say two files, the method doesn't clear the input before...  

When I want to clear() it, it throws an exception...

Is there any way to clear it before i call upload again?

**Comment by ElSnoMan** [comment]
Check out this ChatGPT conversation for some ideas:

https://chatgpt.com/share/66f6c3d6-5fd4-8010-b710-116cc9b21c95
