### ISSUE TITLE
Automate the driver binaries

### ISSUE THREAD

**Issue by ElSnoMan** [ElSnoMan/pyleniumio#43]
`webdriver-manager` package for Python is exactly what we need :D

https://github.com/SergeyPirogov/webdriver_manager

Support out of the box with `webdriver-manager`:

- [x] Chrome
- [x] Firefox
- [x] Internet Explorer
- [x] Opera

**Comment by ysparrow** [comment]
What about using webdriver-manager?  
https://github.com/SergeyPirogov/webdriver_manager

**Comment by ElSnoMan** [comment]
Automating the driver executables is definitely on the roadmap! Pylenium
requires you to have the drivers on your PATH, so this would be a great
step in making it easier. Right now, I mention webdriver-manager in the
Pylenium docs and other options so people can easily install them.
