### ISSUE TITLE
examples/script_sample.py doesn't work

### ISSUE THREAD

**Issue by boakley** [ElSnoMan/pyleniumio#52]
The script_sample.py file doesn't work. It generates the following error because `Pylenium()` is missing some required arguments:

```
$ python examples/script_sample.py 
Traceback (most recent call last):
  File "examples/script_sample.py", line 22, in <module>
    main()
  File "examples/script_sample.py", line 13, in main
    py = Pylenium()
TypeError: __init__() missing 2 required positional arguments: 'config' and 'logger'

```

**Comment by ElSnoMan** [comment]
Good catch! I haven't updated the examples in a long time

**Comment by ElSnoMan** [comment]
Removed stale examples and replaced with some initial examples since the docs do a much better job of going into detail with examples as well.

Fixed in next release
