### ISSUE TITLE
[ Doc, gitbook.it]4. Project Structure with pytest : Typo mistakes

### ISSUE THREAD

**Issue by vishalm** [ElSnoMan/pyleniumio#55]
Project
 conftest.py  # 1
 pylenium.json
 **api_tests.py** -->  **api_tests**
      conftest.py  # 2 
      test_rest_api.py
 ui_tests
      conftest.py  # 3
      test_google.py
test_google.py would have access to fixtures in conftest.py #1 and conftest.py #3
test_rest_api.py would have access to fixtures in conftest.py #1 and **contest.py** #2. --> **conftest.py** #2.

**Comment by ElSnoMan** [comment]
Good catch, @vishalm! I've updated the document:
https://elsnoman.gitbook.io/pylenium/getting-started/project-structure-with-pytest
