### ISSUE TITLE
Native SauceLabs Integration

### ISSUE THREAD

**Issue by ElSnoMan** [ElSnoMan/pyleniumio#84]
https://saucelabs.github.io/sauce_bindings/docs/getting-started

**Comment by nguyet0310** [comment]
I try to integrate it with Lamda test today, but it doesn't work either. The remote browser is `https://username:key@hub.lambdatest.com/wd/hub`
and caps is below
`   "capabilities": {
      
        "build": "Demo Build",
        "name": "Test-Name",
        "platform": "Windows 10",
        "browserName": "Chrome",
        "version": "92.0",
        "resolution": "1024x768"
      
    }`
error as below: `  selenium.common.exceptions.WebDriverException: Message: You might be using selenium 4, please refer to capability generator https://www.lambdatest.com/capabilities-generator for selenium 4 capabilities or contact support`
Will this be supported soon? and mean while, is there any work around solution?

**Comment by ElSnoMan** [comment]
This story is about potentially adding native integration with SauceLabs, not LambdaTest.

Pylenium does work with LambdaTest and our CI actually uses it! The error says to use their capability generator since we're using Selenium 4. Have you tried that? (Could you make this a separate Issue or Discussion please?)

**Comment by ElSnoMan** [comment]
SauceLabs never got back to me with a sandbox account, but Pylenium is flexible enough that it could use SauceLabs if needed. Closing for now
