### ISSUE TITLE
Report Portal integration

### ISSUE THREAD

**Issue by ElSnoMan** [ElSnoMan/pyleniumio#92]
Add ReportPortal.io (RP) integration

Test logs and reports are sent to RP

- [x] Standardize logging to work well with RP
- [x] Attach Screenshots to test failures

CLI commands to make working with RP in Pylenium an easy and elegant experience

- [x] CLI: Command to download docker-compose.yml as docker-compose.report-portal.yml
- [x] CLI: Command to create default pytest.ini (included in `$ pylenium init`)
- [x] CLI: Command to `docker-compose up` the docker-compose.report-portal.yml
- [x]  CLI: Command to tear down RP instance

Documentation/Guides and a video demo

- [x] Switched from `pytest-xdist` to `pytest-parallel`
- [x] Demo and documentation for setting up and using their own ReportPortal instance

**Comment by den-cezar** [comment]
Hi, what plan do on this issue? I'd like have a file HTML, with configurable content inside. Also, nicely see inside it screenshots, on failure tests.

**Comment by ElSnoMan** [comment]
@den-cezar This task is meant to make integrating with Report Portal really easy so users can have a robust reporting instance for the test automation if they want it.

However, if you are needing this right now, you can easily use the existing pytest plugins since Pylenium uses pytest as the test framework.

https://pypi.org/project/pytest-html/
